apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: front-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          # Route vers le Backend (déclarée en premier)
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: back-service
                port:
                  number: 80
          # Route par défaut vers le Frontend Angular
          - path: /
            pathType: Prefix
            backend:
              service:
                name: front-service
                port:
                  number: 80