name: Secret Scanning

on:
    pull_request:
    push:

jobs:
    gitleaks:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - name: Run Gitleaks
              id: gitleaks
              uses: gitleaks/gitleaks-action@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Generate Secrets Job Summary
              if: always()
              run: |
                  echo "## 🔑 Résultat de la Détection de Secrets (Gitleaks)" >> $GITHUB_STEP_SUMMARY
                  echo "" >> $GITHUB_STEP_SUMMARY

                  if [ "${{ steps.gitleaks.outcome }}" == "success" ]; then
                      echo "✅ **Aucun secret ni clé API hardcodée n'a été détecté dans l'historique Git.**" >> $GITHUB_STEP_SUMMARY
                  else
                      echo "⚠️ **Des secrets potentiels ont été identifiés dans le code !**" >> $GITHUB_STEP_SUMMARY
                      echo "Veuillez vérifier les logs de l'action ou l'onglet Security pour révoquer et nettoyer ces clés." >> $GITHUB_STEP_SUMMARY
                  fi
